(define (domain space)
   (:requirements :strips :typing :equality)
   (:types satellite direction instrument mode)
   (:predicates (calibrated ?i)
				(on_board ?i ?s)
				(supports ?i ?m)
				(power_on ?i)
				(pointing ?s ?d)
				(maintenance ?s)
				(have_image ?d ?m))
   (:action turn_to
       :parameters (?s - satellite
					?d1 - direction ?d2 - direction
					)
       :precondition (and (not (= ?d1 ?d2))
						  (pointing ?s ?d1))
       :effect (and (not (pointing ?s ?d1))
					(pointing ?s ?d2)
			   )
   )
   (:action switch-on
       :parameters (?i - instrument ?s - satellite)
       :precondition (on_board ?i ?s)
       :effect (power_on ?i)
   )
   (:action switch-off
       :parameters (?i - instrument ?s - satellite)
       :precondition (and (on_board ?i ?s) (power_on ?i))
       :effect (not (power_on ?i))
   )
   (:action calibrate
       :parameters (?s - satellite ?i - instrument ?d - direction)
       :precondition (and (on_board ?i ?s)
						  (power_on ?i)
						  (pointing ?s ?d))
       :effect (calibrated ?i)
   )
   (:action perfor_maintenance
       :parameters (?s - satellite)
	   :precondition ()
       :effect (maintenance ?s)
   )
   (:action take_image
		:parameters (?s - satellite ?d - direction ?i - instrument ?m - mode)
		:precondition (and (calibrated ?i)
							(on_board ?i ?s)
							(supports ?i ?m)
							(power_on ?i)
							(pointing ?s ?d)
							(maintenance ?s))
		:effect (and (have_image ?d ?m) 
					 (not (maintenance ?s))
				)
	)
)