(define (problem gripper-four-balls)
   (:domain shakey)
   (:objects room1 room2 room3 corridor room4 room5 room6 - room
             box1 box2 - box
             shakey1 - shakey)
   (:init (at-shakey shakey1 corridor)
		  (on-floor shakey1)
          (at-box box1 corridor)  (at-box box2 corridor)
		  (has-door room1 corridor)
		  (has-door room2 corridor)
		  (has-door room3 corridor)
		  (has-door room4 corridor)
		  (has-door room5 room4)
		  (has-door room5 room6)
		  (has-door room6 corridor)
		  (has-door corridor room1)
		  (has-door corridor room2)
		  (has-door corridor room3)
		  (has-door corridor room4)
		  (has-door room4 room5)
		  (has-door room6 room5)
		  (has-door corridor room6)
   )
   (:goal (and (switched room1)
			   (switched room2)
			   (switched room3)
			   (switched room4)
			   (switched room5)
			   (switched room6)
			   (switched corridor)
          )
   )
)