(define (problem gripper-four-balls)
   (:domain shakey)
   (:objects room1 room2 room3 room4 corridor - room
             box1 box2 - box
             shakey1 - shakey)
   (:init (at-shakey shakey1 room1)
		  (on-floor shakey1)
          (at-box box1 room1)  (at-box box2 room1)
		  (has-door room1 corridor)
		  (has-door room2 corridor)
		  (has-door room3 corridor)
		  (has-door room4 corridor)
		  (has-door corridor room1)
		  (has-door corridor room2)
		  (has-door corridor room3)
		  (has-door corridor room4)
   )
   (:goal (and (switched room1)
			   (switched room2)
			   (switched room3)
			   (switched room4)
			   (switched corridor)
          )
   )
)