(define (domain blocks)
  (:requirements :strips :typing)
     (:types block)
  (:predicates 
         (on ?x ?y)
         (ontable ?x)
         (clear ?x)
         (handempty)
         (holding ?x)
         )
  (:action pick-up
       :parameters (?x -  block)
       :precondition (and (clear ?x) (ontable ?x) (handempty))
       :effect (and (not (ontable ?x))
                    (not (clear ?x))
                    (not (handempty))
                    (holding ?x))
   )
  (:action unstack
       :parameters (?x ?y - block)
       :precondition (and (on ?x ?y) (clear ?x) (handempty))
       :effect (and (holding ?x)
                    (clear ?y)
                    (not (clear ?x))
                    (not (handempty))
                    (not (on ?x ?y)))
   )  
  (:action stack
       :parameters (?x ?y - block)
       :precondition (and (clear ?y) (holding ?x))
       :effect
       (and  (not (holding ?x))
			 (not (clear ?y))
			 (clear ?x)
			 (handempty)
			 (on ?x ?y)
       )
   )
  (:action put-down
       :parameters (?x - block)
       :precondition (holding ?x)
       :effect
       (and (ontable ?x)
			(handempty)
			(clear ?x)
			(not (holding ?x))
       )
   )  
)