(define (domain rover)
   (:requirements :strips :typing :equality)
   (:types rover location)
   (:predicates (at-rover ?r ?l)
				(have_image ?l)
				(drilled ?l)
				(communicated ?l)
				(analysed ?l)
   )
   (:action move
       :parameters (?r - rover ?l1 - location ?l2 - location)
       :precondition (and (not (= ?l1 ?l2))
						  (at-rover ?r ?l1)
					 )
       :effect (and (at-rover ?r ?l2)
                    (not (at-rover ?r ?l1))
               )
   )
   (:action take-a-picture
       :parameters (?r - rover ?l - location)
       :precondition (at-rover ?r ?l)
       :effect (have_image ?l)
   )
   (:action drill
       :parameters (?r - rover ?l - location)
       :precondition (at-rover ?r ?l)
       :effect (drilled ?l)
   )
   (:action earth-communication
       :parameters (?r - rover ?l - location)
       :precondition (and (at-rover ?r ?l)
                          (analysed ?l)
						  (have_image ?l)
                     )
       :effect (communicated ?l)
   )
   (:action analyse-samples
       :parameters (?r - rover ?l - location)
       :precondition (and (at-rover ?r ?l)
                          (drilled ?l)
                     )
       :effect (analysed ?l)
   )
)