(define (domain gripper)
	(:requirements :typing :durative-actions :fluents :durative-actions :constraints :preferences)
	(:types room ball gripper)
	(:predicates (at-robby ?r - room)
                 (at-ball ?b - ball ?r - room)
                 (free ?g - gripper)
                 (carry ?g - gripper ?b - ball))
	(:functions
		(dur-ball ?ball - ball)
	)
	(:action move
		:parameters (?x - room ?y - room)
		:precondition (at-robby ?x)
		:effect (and (at-robby ?y)
                     (not (at-robby ?x))
                )
    )
    (:durative-action pick-up
		:parameters (?ball - ball ?room - room ?gripper - gripper)
		:duration (= ?duration (dur-ball ?ball))
		:condition (and (at start (at-ball ?ball ?room))
						(at start (free ?gripper))
						(over all (at-robby ?room))
                   )
		:effect (and (at start (not (at-ball ?ball ?room))) 
                     (at start (not (free ?gripper))) 
					 (at end (carry ?gripper ?ball))
                )
	)
	(:durative-action drop
		:parameters (?ball - ball ?room - room ?gripper - gripper)
		:duration (= ?duration (dur-ball ?ball))
		:condition (and (at start (carry ?gripper ?ball))
                        (over all (at-robby ?room))
                   )
		:effect (and (at start (not (carry ?gripper ?ball)))
					 (at end (at-ball ?ball ?room))
                     (at end (free ?gripper))
                )
    )
)