(define (problem gripper-four-balls)
   (:domain gripper)
   (:objects kitchen living-room bathroom - room
             Z1 Z2 - ball
             left right - gripper)
   (:init (at-robby kitchen)
          (free left)            (free right)
          (at-ball Z1 kitchen)  (at-ball Z2 kitchen)
		  (= (dur-ball Z1) 10)
		  (= (dur-ball Z2) 20)
   )
   (:goal (and (at-ball Z1 living-room)
               (at-ball Z2 living-room)
          )
   )
   (:constraints (and ;(preference PLACED (at end (at-robby living-room)))
					  (preference PLACED (sometime (at-robby bathroom)))
				 )
   )
)